### ISSUE TITLE
File Not Found, falling at the first hurdle

### ISSUE THREAD

**Issue by Heard-of-Checkerboard** [perfanalytics/pose2sim#186]
Hello all,

I'm trying to use my own data from DeepLabCut of a hand moving over a desk as a test for future work with birds. I'm pretty sure I've set up the necessary files, including sourcing a calibration TOML from AniPose and translating the h5 pose files. However, I can't even get started because I keep getting a "FileNotFound" error with the Config file when I attempt to calibrate or  #perform pose estimation. I've gone through the motions of determining that I'm in the right directory and that the files are in that directory, but the error won't go away. What step did I miss to dictate the use of my custom Config file? 

I'm sure this is a really simple issue, but I'm not a programmer and I've been using Python for less than a month. 

(Also my sincerest apologies to David for emailing earlier, there's really no excuse for that.)

**Comment by davidpagnon** [comment]
Hi, no problem!

I answerd by email but I'll copy-paste it here in case it helps other people:

For Pose2Sim to work, you need a directory structure with at least a Configuration file, a calibration folder, and a video folder.
You can copy-paste the directories wherever you want, and replace the files with the proper ones. You will probably need to change the calibration parameters of your configuration file (convert -> calculate, and edit the dimensions of your checkerboard and scene points).
Then, you need to open your Anaconda prompt in the right folder. Do `cd <PATH_TO_YOUR_FOLDER`, and then open your python command and follow the tutorial.

I hope it helps!

**Comment by Heard-of-Checkerboard** [comment]
Hi David,
Thank you for responding on both channels, I appreciate that. 

I've set up my folders as you suggested, but I'm still getting this error. What's interesting, if I replace the Config file from one of the demo folders with my own, I get the same error again. If I switch it back the error goes away. It's as if the system can't recognise my own file at all. 

I'm also trying to work with custom DeepLabCut and OpenSim models, but I feel like that is unrelated for now. 

Would it be useful to attach my file for you to test?

Thank you for the help so far, hopefully we can work through this!

**Comment by davidpagnon** [comment]
Can ypu first send me your full error log?

**Comment by Heard-of-Checkerboard** [comment]
Sure, it's

`In[1]:    from Pose2Sim import Pose2Sim
 In[2]:    Pose2Sim.poseEstimation()
---------------------------------------------------------------------------------------------------
FileNotFoundError                                                                Traceback (most recent call last)
File ~\minoconda3\envs\Pose2Sim\lib\site-packages\Pose2Sim\Pose2Sim.py:135, in read_config_files(config)
      133 try:
      134      #if batch
--> 135      session_config_dict = toml.load(os.path.join(config_dir, '..','Config.toml'))
      136      trial_config_dict = toml.load(os.path.join(config_dir, 'Config.toml'))

File ~\miniconda3\envs\Pose2Sim\lib\site-packages-toml\decoder.py:133, in load(f, _dict, decoder)
      132 if_ispath(f):
--> 133     with io.open(_getpath(f), econding='utf-8') as ffile:
      134              return loads(ffile.read(), _dict, decoder)

FileNotFoundError: [Errno 2} No such file or directory: '.\\..\\Config.toml'

During the handling of the above exception, another exception occured:

TomlDecodeError                                                                   Traceback (most recent call last)
Cell In[2], line 1
----> 1 Pose2Sim.poseEstimation()

File ~\miniconda3\envs\Pose2Sim\lib\site-packages\Pose2Sim\Pose2Sim.py:372, in poseEstimation(config)
       371 def poseEstimation(config=None):
--> 372        pipeline = Pose2SimPipeline(config)
       373       pipeline.poseEstimation()

File ~\miniconda3\envs\Pose2Sim\lib\site-packages\Pose2Sim\Pose2Sim.py:163, in Pose2SimPipeline.__init__(self, config)
       162 def __init__(self, config=None):
-->  163      self.level, self.config_dicts = read_config_files(config)
       164       try:
       165            self.session_dir = os.path.realpath([os.getcwd() if self.level==2 else os.path.jion(os.getcwd(), '..')][0])

File ~\miniconda3\envs\Pose2Sim\lib\site-packages\Pose2Sim\Pose2Sim.py:140, in read_config_files(config)
       137      session_config_dict = recursive_update(session_config_dict,trial_config_dict)
       138 except:
       139         # if single trial
-->  140         session_config_dict = toml.load(os.path.join(config_dir, 'Config.toml'))
       141 session_config_dict.get("project").update({"project_dir":config})
       142 config_dicts = [session_config_dict]

File ~\miniconda3\envs\Pose2Sim\lib\site-packages\toml\decoder.py:134, in load(f, _dict, decoder)
       132 if _ispath(f):
       133      with io.open(_getpath(f), encoding='utf-8') as ffile:
-->  134            return loads(ffile.read(), _dict, decoder)
       135 elif isinstance(f, list):
       136       from os import path as op

File ~\miniconda3\envs\Pose2Sim\lib\site-packages\toml\decoder.py:340, in loads(s, _dict, decoder)
       338 if openstring or multilinestr:
       339        if not multilinestr:
-->  340              raise TomlDecodeError("unbalanced quotes", original, i)
       341        if ((sl[i - 1] == "'" or sl[i - 1] == '"') and (
       342                  sl[i - 2] == sl[i - 1])):
       343              sl[i] = sl[i - 1]

TomlDecodeError: Unbalanced quotes (line 277 column 18 char 17187)`

At least that's what it looks like when I copy-paste it here. Part of this I recognise as my own syntax error in writing the new Config file for my own data, but the first bit I'm clueless.

**Comment by davidpagnon** [comment]
Are you sure you are running from the right folder? Can you do `pwd` when you are in the python command line, and tell me where your custom directory is?

By the way, if you ran and converted files from DeepLabCut, no need to run pose estimation. Same if you calibrated from anoposelib. And same if you have a single person, natively synchronized cameras, etc. You might just need to run Pose2Sim.triangulation().

Note that you can also try to run hand detection natively from Pose2Sim. You will have to set `pose_model = Hand` and `mode=lightweight`. Not sure it is good enough, but I'm curious to hear how it goes!
(you could also retrain the model in balanced or performance mode with MMPose, but I'm not sure you are ready for this yet)

**Comment by Heard-of-Checkerboard** [comment]
After running `pwd` the output was 
`C:\\Users\\andjs\\miniconda3\\envs\\Pose2Sim\\Lib\\site-packages\\Pose2Sim\\Demo_handtest`
which is my custom directory. 

You're probably right that I'm okay skipping ahead to triangulation with how much back-end stuff I've run, but I wanted to test the system to see if it was working the way it was supposed to. Also the error persisted when I tried that, so I'm not sure I've left square one yet. 

I'll try running my footage with `pose_model = Hand` for now just to make sure there isn't something completely wrong behind the scenes, but I'm going to eventually need to run footage of birds in flight, which DeepLabCut is might be better suited to. 
(I'm not sure I'm ready for MMPose either)

**Comment by davidpagnon** [comment]
Okay, I'm running out of ideas, you can send me your folder if you are okay with it :)

**Comment by Heard-of-Checkerboard** [comment]
Sure thing David, I'll zip up everything I can and email it to you (the folders keep failing to upload here). Thank you so much for sticking with me on this! 

I'll also say that running `pose_model = Hand` didn't work, but it seems like every model that isn't `Body_with_feet` is also causing problems. The error is massively long so I won't include it, but I think it stems from the system failing to download the model properly, which is another mystery.

**Comment by davidpagnon** [comment]
Hi, I just had a look, your problem comes from your Config.toml file. The strings were not closed in several instances:
- For example, in the definition of your CUSTOM model, you had `  name = "mcarp_2` (mcarp_2 is never closed), and same in other instances
- At some point, you spelled CUCTOM instead of CUSTOM
- Python is very specific about its use of spaces and tabs. There are cases where you had tabs instead of 4 spaces, and line 285, you had 5 spaces instead of 4.
- You cannot run pose estimation with Pose2Sim, unless it is an onnx/zip file deployed from MMPose (RTMPose, RTMO, etc). So you need to keep "mode" commented

I don't know which text editor you are using, but I would recommend you to make sure you have syntactic coloring for toml files, as unmatched quotes would become more visible.

Here is the corrected table:

```toml
[pose.CUSTOM]
name = "wrist"
id = 0
  [[pose.CUSTOM.children]]
  name = "mcarp_1"
  id = 1
     [[pose.CUSTOM.children.children]]
     name = "pphal_1"
     id = 2
        [[pose.CUSTOM.children.children.children]]
        name = "dphal_1"
        id = 3
  [[pose.CUSTOM.children]]
  name = "mcarp_2"
  id = 4
    [[pose.CUSTOM.children.children]]
    name = "pphal_2"
    id = 5
        [[pose.CUSTOM.children.children.children]]
        name = "mphal_2"
        id = 6
           [[pose.CUSTOM.children.children.children.children]]
           name = "dphal_2"
           id = 7
  [[pose.CUSTOM.children]]
  name = "mcarp_3"
  id = 8
     [[pose.CUSTOM.children.children]]
     name = "pphal_3"
     id = 9
        [[pose.CUSTOM.children.children.children]]
        name = "mphal_3"
        id = 10
           [[pose.CUSTOM.children.children.children.children]]
           name = "dpahl_3"
           id = 11
  [[pose.CUSTOM.children]]
  name = "mcarp_4"
  id = 12
     [[pose.CUSTOM.children.children]]
     name = "pphal_4"
     id = 13
        [[pose.CUSTOM.children.children.children]]
        name = "mphal_4"
        id = 14
           [[pose.CUSTOM.children.children.children.children]]
           name = "dpahl_4"
           id = 15
  [[pose.CUSTOM.children]]
  name = "mcarp_5"
  id = 16
     [[pose.CUSTOM.children.children]]
     name = "pphal_5"
     id = 17
        [[pose.CUSTOM.children.children.children]]
        name = "mphal_5"
        id = 18
           [[pose.CUSTOM.children.children.children.children]]
           name = "dphal_5"
           id = 19
```

---

Then there was another problem: the likelihoods estimated by DeepLabCut were generally pretty low, so I set `likelihood_threshold_triangulation = 0`. The triangulation results were still not good, so I checked the calibration data and the pose estimation results. I think the model you trained is not very good: when I run `json_display_without_img -j <JSON_FOLDER>, the points are mostly red and do not move like a hand. 

https://github.com/user-attachments/assets/6fcad129-5702-4485-be02-9948d15c2e30

So I tried to run with the native `pose_mode = 'Hand'` and `mode = 'lightweight'`. Results are not great because the hand model is not good, but at least we've got something. 
https://github.com/user-attachments/assets/cb09f60a-b3ac-46c5-8b74-0dddce9b0c57

Be aware that I had to edit a few lines in triangulation.py, and that I have not pushed the change yet. If you want to try it, do `pip show pose2sim` to find where your file is stored, and replace the 3 lines after L708 with those:
```python
    try:
        keypoints_names_swapped = ['L'+keypoint_name[1:] if keypoint_name.startswith('R') else 'R'+keypoint_name[1:] if keypoint_name.startswith('L') else keypoint_name for keypoint_name in keypoints_names]
        keypoints_names_swapped = [keypoint_name_swapped.replace('right', 'left') if keypoint_name_swapped.startswith('right') else keypoint_name_swapped.replace('left', 'right') if keypoint_name_swapped.startswith('left') else keypoint_name_swapped for keypoint_name_swapped in keypoints_names_swapped]
        keypoints_idx_swapped = [keypoints_names.index(keypoint_name_swapped) for keypoint_name_swapped in keypoints_names_swapped] # find index of new keypoint_name
    except:
        keypoints_names_swapped = keypoints_names
        keypoints_idx_swapped = keypoints_idx
        logging.warning('No left/right swap was performed.')
```

However, I would recommend you downloading the Hand model from DeepLabCut, as it seems to be better. See this to find it:
https://anipose.readthedocs.io/en/latest/tutorial.html#generating-2d-labels:~:text=We%20have%20prepared,Anipose%20project%20folder.
